### PR TITLE
fix empty array issue

### LINKED ISSUE #59: GET /tentants/{id}/apis Return body is inconsistent
GET /apis returns an [] of JSON objects when there are >=1 APIs defined for the specified tentant id.

Howerver, a {} is returned when there are 0 APIs defined.  The expected return value is [].

### PR DESCRIPTION
**Pull request by taylorking**
Fixes #59 this might be controversial.. Comments are welcome

### CODE REVIEW

File: api-gateway-config/scripts/lua/management/apis.lua [hunk 1]
```diff
@@ -287,7 +287,11 @@ function getAllAPIs(queryParams)
         apiList[#apiList+1] = cjson.decode(v)
       end
     end
-    apiList = cjson.encode(apiList)
+    if next(apiList) == nil then
+      apiList = "[]"
```
Comment (alexsong93) [inline api-gateway-config/scripts/lua/management/apis.lua]: hmm interesting approach. @mdeuser would this work for your OpenWhisk test cases?

**Comment by taylorking** [comment]
Updated, check and see that it looks good
