### PR TITLE
Redis routing fix for backend proxy

### LINKED ISSUE #82: Proxy functionality not picking up url after basepath
Steps to reproduce:

Request:

POST /v1/apis
```
{
  "name": "testAPI",
  "basePath": "/foo",
  "tenantId": "01c2ed30-f9d7-4d7e-93fc-46b94cb719a0",
  "resources": {
    "/bar": {
      "operations": {
        "GET": {
          "backendMethod": "get",
	  "backendUrl": "http://httpbin.org",
	  "policies": []
        }
      }
    }
  }
}
```
Response:
```
{
  "managedUrl": "http://0.0.0.0:8080/api/01c2ed30-f9d7-4d7e-93fc-46b94cb719a0/test",
  "tenantId": "01c2ed30-f9d7-4d7e-93fc-46b94cb719a0",
  "id": "263926f1-4d4d-4ae5-85cf-8c42547abb82",
  "basePath": "/foo",
  "name": "testAPI",
  "resources": {
    "/bar": {
      "operations": {
        "GET": {
          "policies": {},
          "backendMethod": "get",
          "backendUrl": "http://httpbin.org"
        }
      }
    }
  }
}
```

Invoke API:
GET http://0.0.0.0:8080/api/01c2ed30-f9d7-4d7e-93fc-46b94cb719a0/foo/bar/get

Expectation:
Should proxy request to httpbin.org/get

Returns:
404 Error: not found

### PR DESCRIPTION
**Pull request by alexsong93**
Fixes #82 and #80.
1) Due to bad regex handling, the gateway wasn't able to proxy properly to the backend (#82). Based on discussion with @mhamann and @codymwalker, modified `routing.lua` to find the correct redis key based on the number of slashes in basePath + resourcePath
2) Updated how path parameter is handled with the new design
3) Also fixed the cases where the resource path is just a single "/" (#80)

@mhamann @codymwalker @DavidMGreen PTAL

### CODE REVIEW

**Comment by alexsong93** [comment]
@mhamann Added additional unit tests for the routing logic

File: api-gateway-config/scripts/lua/routing.lua [hunk 1]
```diff
@@ -88,33 +82,73 @@ function processCall()
...
+  -- Find the correct redisKey
+  local redisKey = utils.concatStrings({"resources:", tenant, ":", path})
+  local _, count = string.gsub(redisKey, "/", "")
+  for i = count, 0, -1 do
+    local countString = tostring(i)
+    if keyTable[countString] ~= nil then
+      for _, key in pairs(keyTable[countString]) do
+        -- Check for exact match or path parameter match
+        if key == redisKey or key == utils.concatStrings({redisKey, "/"}) or _M.pathParamMatch(key, redisKey) == true then
+          local res = {string.match(key, "([^:]+):([^:]+):([^:]+)")}
```
Comment (mhamann) [inline api-gateway-config/scripts/lua/routing.lua]: This will be brittle if we ever change the way data flows into redis or allow changing the backend.
